import {chromium} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const env=Object.fromEntries(readFileSync(new URL('../../../.env',import.meta.url),'utf8').split(/\r?\n/).filter(l=>l&&!l.startsWith('#')).map(l=>{const n=l.indexOf('=');return [l.slice(0,n),l.slice(n+1)];}));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1512,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(process.env.WEB_URL||'http://localhost:5173');
 await page.getByLabel('Рабочая почта').fill(env.ADMIN_INITIAL_EMAIL);
 await page.getByLabel('Пароль',{exact:true}).fill(env.ADMIN_INITIAL_PASSWORD);
 await page.getByRole('button',{name:'Войти в систему'}).click();
 await page.getByRole('heading',{name:'Обзор рабочего дня'}).waitFor();
 await page.getByRole('heading',{name:'Динамика обращений'}).waitFor();
 await page.locator('table tbody tr').first().waitFor();
 mkdirSync(new URL('../../../docs/screenshots/',import.meta.url),{recursive:true});
 await page.screenshot({path:new URL('../../../docs/screenshots/dashboard.png',import.meta.url).pathname,fullPage:true});
 for(const label of ['Сотрудники','АХО / Получатели','Департаменты','Категории','Аналитика','SLA','Отчеты','Журнал действий','Настройки']){
  await page.locator('nav').getByRole('button',{name:label,exact:true}).click();
  await page.getByRole('heading',{name:label,exact:true}).first().waitFor();
  await page.waitForTimeout(180);
  assert.equal(await page.locator('.error').count(),0,`Error on page ${label}`);
 }
 await page.locator('nav').getByRole('button',{name:'Заявки',exact:true}).click();
 await page.getByRole('button',{name:'Новая заявка',exact:true}).click();
 await page.getByLabel('Описание проблемы').fill('Проверка E2E: в кабинете 305 не работает кондиционер.');
 await page.getByLabel('Здание',{exact:true}).fill('Главный офис');
 await page.getByLabel('Этаж',{exact:true}).fill('3');
 await page.getByLabel('Кабинет',{exact:true}).fill('305');
 await page.getByRole('button',{name:'Проверить заявку'}).click();
 await page.getByRole('button',{name:'Отправить заявку',exact:true}).click();
 await page.getByRole('heading',{name:/AHO-\d{4}-\d{6}/}).waitFor();
 const number=await page.getByRole('heading',{name:/AHO-\d{4}-\d{6}/}).textContent();
 await page.getByRole('button',{name:'Принять заявку',exact:true}).click();
 await page.getByRole('button',{name:'Начать / продолжить работу'}).click();
 await page.getByRole('button',{name:'Запросить информацию',exact:true}).click();
 await page.getByLabel('Комментарий / причина').fill('Уточните время возникновения проблемы');
 await page.getByRole('button',{name:'Подтвердить',exact:true}).click();
 await page.getByLabel('Комментарий',{exact:true}).fill('Проблема появилась сегодня утром');
 await page.getByRole('button',{name:'Отправить',exact:true}).click();
 await page.getByRole('button',{name:'Начать / продолжить работу'}).click();
 await page.getByRole('button',{name:'Завершить работу',exact:true}).click();
 await page.getByLabel('Комментарий / причина').fill('Фильтр заменен. Работа восстановлена.');
 await page.getByRole('button',{name:'Подтвердить',exact:true}).click();
 await page.getByRole('button',{name:'Все выполнено',exact:true}).click();
 await page.getByRole('button',{name:'Оценить 5',exact:true}).click();
 await page.getByText('Ваша оценка',{exact:true}).waitFor();
 assert.equal(await page.locator('.detail-heading .badge').textContent(),'Закрыта');
 assert.equal(errors.length,0,errors.join('\n'));
 await page.screenshot({path:new URL('../../../docs/screenshots/ticket.png',import.meta.url).pathname,fullPage:true});
 await page.getByRole('button',{name:'К списку заявок'}).click();
 await page.getByLabel('Поиск заявок').fill(number);
 await page.waitForTimeout(400);
 assert.equal(await page.locator('tbody tr').count(),1);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:new URL('../../../docs/screenshots/mobile.png',import.meta.url).pathname,fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 console.log('PASS: authenticated pages, DB-backed create/accept/start/question/reply/complete/confirm/rate, filters, responsive viewport, no browser exceptions.');
}finally{await browser.close();}
